#  Source:  https://github.com/deconz-community/deconz-docker#running-the-deconz-container
name: deconz-beta
services:
  deconz-beta:
    image: docker.io/deconzcommunity/deconz:beta
    #image: ghcr.io/deconz-community/deconz-docker:beta
    container_name: deconz-beta
    ports:
      - "8001:80"    #  Phoscon GUI
      - "8443:443"   #  Phoscon GUI ?
      - "5900:5900"  #  VNC access to DeCONZ
      #- "6080:6080"  # This offers a http access to the VNC server
    environment:
      #- DEBUG_APS=0
      #- DEBUG_DDF=0
      #- DEBUG_DEV=0
      #- DEBUG_ERROR=0
      #- DEBUG_HTTP=0
      #- DEBUG_INFO=1
      #- DEBUG_OTA=0
      #- DEBUG_ZCL=0
      #- DEBUG_ZDP=0
      #
      #- DECONZ_DEVICE=/dev/ttyACM0    # The mounted ConBee II USB device
      #- DECONZ_UID=1000
      #- DECONZ_GID=1000
      #
      - DECONZ_VNC_MODE=1	            # Enable VNC server
      #- DECONZ_VNC_PORT=5900
      #- DECONZ_VNC_DISPLAY=0
      - DECONZ_VNC_PASSWORD=phoscon
      #- DECONZ_VNC_DISABLE_PASSWORD=0
      #- DECONZ_VNC_PASSWORD_FILE=/path/to/file
      #- DECONZ_NOVNC_PORT=6080       # This offers a http access to the VNC server
      #
      #- DECONZ_WEB_PORT=80
      #- DECONZ_WS_PORT=443
      #- DECONZ_UPNP=1
      #
      #- DECONZ_START_VERBOSE=0
      - TZ=Europe/Berlin
    privileged: true
    volumes:
      - ~/.config/containers/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0                  # The mounted ConBee II USB device
    restart: unless-stopped
